name: algoredo
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  graph_collection: ^1.1.2
  directed_graph: ^0.3.5


dev_dependencies:
  pedantic: ^1.10.0

